from __future__ import annotations

import datetime as dt
from typing import Callable

from nexuscore.core.message import Event
from nexuscore.core.uuid import UUID4


class Clock:
    @property
    def timer_names(self) -> list[str]: ...
    @property
    def timer_count(self) -> int: ...
    def timestamp(self) -> float: ...
    def timestamp_ms(self) -> int: ...
    def timestamp_us(self) -> int: ...
    def timestamp_ns(self) -> int: ...
    def utc_now(self) -> dt.datetime: ...
    def local_now(self, tz: dt.tzinfo | None = ...) -> dt.datetime: ...
    def register_default_handler(self, handler: Callable[[TimeEvent], None]) -> None: ...
    def next_time_ns(self, name: str) -> int: ...
    def set_time_alert(
        self,
        name: str,
        alert_time: dt.datetime | int,
        callback: Callable[[TimeEvent], None] | None = ...,
        override: bool = ...,
        allow_past: bool = ...,
    ) -> None: ...
    def set_time_alert_ns(
        self,
        name: str,
        alert_time_ns: int,
        callback: Callable[[TimeEvent], None] | None = ...,
        allow_past: bool = ...,
    ) -> None: ...
    def set_timer(
        self,
        name: str,
        interval: dt.timedelta,
        start_time: dt.datetime | None = ...,
        stop_time: dt.datetime | None = ...,
        callback: Callable[[TimeEvent], None] | None = ...,
        allow_past: bool = ...,
        fire_immediately: bool = ...,
    ) -> None: ...
    def set_timer_ns(
        self,
        name: str,
        interval_ns: int,
        start_time_ns: int,
        stop_time_ns: int,
        callback: Callable[[TimeEvent], None] | None = ...,
        allow_past: bool = ...,
        fire_immediately: bool = ...,
    ) -> None: ...
    def cancel_timer(self, name: str) -> None: ...
    def cancel_timers(self) -> None: ...


def register_component_clock(instance_id: UUID4, clock: Clock) -> None: ...
def deregister_component_clock(instance_id: UUID4, clock: Clock) -> None: ...
def remove_instance_component_clocks(instance_id: UUID4) -> None: ...
def set_backtest_force_stop(value: bool) -> None: ...
def is_backtest_force_stop() -> bool: ...


class LiveClock(Clock):
    def __init__(self) -> None: ...


class TimeEvent(Event):
    def __init__(self, name: str, event_id: UUID4, ts_event: int, ts_init: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def id(self) -> UUID4: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def ts_init(self) -> int: ...
