from __future__ import annotations

from typing import Any, Callable

from nexuscore.common.component import Clock
from nexuscore.core.message import Request, Response
from nexuscore.core.uuid import UUID4
from nexuscore.model.identifiers import TraderId
from nexuscore.serialization.base import Serializer


class MessageBus:
    def __init__(
        self,
        trader_id: TraderId,
        clock: Clock,
        instance_id: UUID4 | None = ...,
        name: str | None = ...,
        serializer: Serializer | None = ...,
        config: Any | None = ...,
    ) -> None: ...
    def endpoints(self) -> list[str]: ...
    def topics(self) -> list[str]: ...
    def subscriptions(self, pattern: str | None = ...) -> list[Subscription]: ...
    def streaming_types(self) -> set[type]: ...
    def has_subscribers(self, pattern: str | None = ...) -> bool: ...
    def is_subscribed(self, topic: str, handler: Callable[[Any], None]) -> bool: ...
    def is_pending_request(self, request_id: UUID4) -> bool: ...
    def is_streaming_type(self, cls: type) -> bool: ...
    def dispose(self) -> None: ...
    def register(self, endpoint: str, handler: Callable[[Any], None]) -> None: ...
    def deregister(self, endpoint: str, handler: Callable[[Any], None]) -> None: ...
    def add_streaming_type(self, cls: type) -> None: ...
    def send(self, endpoint: str, msg: Any) -> None: ...
    def request(self, endpoint: str, request: Request) -> None: ...
    def response(self, response: Response) -> None: ...
    def subscribe(self, topic: str, handler: Callable[[Any], None], priority: int = ...) -> None: ...
    def unsubscribe(self, topic: str, handler: Callable[[Any], None]) -> None: ...
    def publish(self, topic: str, msg: Any, external_pub: bool = ...) -> None: ...
    def publish_batch(self, topic: str, msgs: list[Any], external_pub: bool = ...) -> None: ...


def is_matching_py(topic: str, pattern: str) -> bool: ...


class Subscription:
    topic: str
    handler: Callable[[Any], None]
    priority: int
    def __init__(self, topic: str, handler: Callable[[Any], None], priority: int = ...) -> None: ...
